name: Example Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run example action
        uses: ./actions/my-action
        with:
          example_input: 'Hello, World!'